# Generated by Django 3.1.1 on 2020-09-27 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrapingApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cars',
        ),
    ]
