# Generated by Django 3.1.1 on 2020-09-27 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrapingApp', '0002_delete_cars'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parliament',
            options={},
        ),
    ]
