# Generated by Django 3.1.1 on 2020-09-27 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapingApp', '0003_auto_20200927_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parliament',
            name='date_born',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterModelTable(
            name='parliament',
            table=None,
        ),
    ]
