# Generated by Django 3.1.1 on 2020-09-27 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrapingApp', '0004_auto_20200927_1559'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Parliament',
        ),
    ]
