# Generated by Django 3.1.1 on 2020-09-27 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrapingApp', '0007_auto_20200927_1602'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='parliament1',
            table=None,
        ),
    ]
