# Generated by Django 3.1.1 on 2020-09-27 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrapingApp', '0009_auto_20200927_1609'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Parliament1',
        ),
    ]
