# Generated by Django 3.1.1 on 2020-09-27 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scrapingApp', '0010_delete_parliament1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parliament1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('date_born', models.CharField(blank=True, max_length=10, null=True)),
                ('place_born', models.CharField(blank=True, max_length=50, null=True)),
                ('profession', models.CharField(blank=True, max_length=80, null=True)),
                ('lang', models.CharField(blank=True, max_length=70, null=True)),
                ('party', models.CharField(blank=True, max_length=80, null=True)),
                ('email', models.CharField(blank=True, max_length=80, null=True)),
                ('fb', models.CharField(blank=True, max_length=80, null=True)),
                ('url', models.TextField(blank=True, max_length=15, null=True)),
            ],
        ),
    ]
