# Generated by Django 3.1.1 on 2020-09-27 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapingApp', '0011_parliament1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parliament1',
            name='date_born',
            field=models.DateField(blank=True, null=True),
        ),
    ]
