# Generated by Django 3.1.1 on 2020-09-27 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrapingApp', '0014_parliament1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Parliament1',
        ),
    ]
