# Generated by Django 3.1.1 on 2020-09-27 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrapingApp', '0016_parliament1'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='parliament1',
            table='Parliament1',
        ),
    ]
