# Generated by Django 3.1.1 on 2020-09-28 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapingApp', '0017_auto_20200927_1620'),
    ]

    operations = [
        migrations.CreateModel(
            name='TheodoTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('image', models.CharField(max_length=150)),
                ('fun_fact', models.TextField(blank=True)),
            ],
        ),
    ]
